# Generated by Django 5.2 on 2025-05-06 08:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('country_code', models.CharField(max_length=3, unique=True)),
                ('region', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevelopmentStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Equipement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='GedOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('common_name', models.CharField(blank=True, max_length=255, null=True)),
                ('scientific_name', models.CharField(blank=True, max_length=255, null=True)),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
        migrations.CreateModel(
            name='FundingSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('funding_type', models.CharField(choices=[('Government', 'Government'), ('Donor', 'Donor'), ('Private', 'Private'), ('Multilateral', 'Multilateral')], max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.country')),
            ],
        ),
        migrations.CreateModel(
            name='CountryGedOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Under Research', 'Under Research'), ('In Trials', 'In Trials'), ('Approved', 'Approved'), ('Potential', 'Potential')], max_length=100)),
                ('challenge', models.TextField(blank=True, null=True)),
                ('trait_improvement', models.TextField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.country')),
                ('ged_organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.gedorganism')),
            ],
        ),
        migrations.CreateModel(
            name='HumanCapacity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_biotech_experts', models.IntegerField(default=0)),
                ('num_gene_editing_specialists', models.IntegerField(default=0)),
                ('num_research_students', models.IntegerField(default=0)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landscape.country')),
            ],
        ),
        migrations.CreateModel(
            name='Literature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_file', models.FileField(upload_to='documents/')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.country')),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('government', 'Government'), ('regulatory', 'Regulatory'), ('university', 'University'), ('research', 'Research'), ('private_sector', 'Private Sector'), ('development_agency', 'Development Agency')], default='government', max_length=20, verbose_name='Organization Type')),
                ('focus_area_in_ged', models.TextField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.country')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('nature_of_partnership', models.CharField(max_length=100, unique=True)),
                ('project_duration', models.IntegerField(default=0)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landscape.country')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectFunding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount_in_usd', models.FloatField(default=0.0)),
                ('organization_funding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.organization')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.project')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectOrganism',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trait', models.CharField(blank=True, max_length=255, null=True)),
                ('development_stage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.developmentstage')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.gedorganism')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.project')),
                ('technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.equipement')),
            ],
        ),
        migrations.CreateModel(
            name='RegulatoryFramework',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('KeyAuthorityLegislation', models.TextField(blank=True, null=True)),
                ('has_ged_policy', models.BooleanField(default=False)),
                ('RegulatorStatus', models.TextField(blank=True, null=True)),
                ('framework_summary', models.TextField(blank=True, null=True)),
                ('year_enacted_published', models.DateField(blank=True, null=True)),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.country')),
            ],
        ),
    ]
