# Generated by Django 5.2 on 2025-05-06 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='country',
            name='region',
            field=models.CharField(max_length=100),
        ),
    ]
