# Generated by Django 5.2 on 2025-05-06 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0002_alter_country_region'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='nature_of_partnership',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
