# Generated by Django 5.2 on 2025-05-06 15:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0003_alter_project_nature_of_partnership'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectorganism',
            name='technology',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='landscape.equipement'),
        ),
    ]
