# Generated by Django 5.2 on 2025-05-10 22:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0005_remove_project_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='humancapacity',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='landscape.country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
