# Generated by Django 5.2 on 2025-05-10 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0006_alter_humancapacity_country_alter_project_country_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name',
            field=models.CharField(max_length=300, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('Not started)', 'Not started'), ('Started', 'Started'), ('Ongoing', 'Ongoing'), ('Completed', 'Completed')], max_length=100, null=True),
        ),
    ]
