# Generated by Django 5.2 on 2025-05-12 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0007_alter_project_name_alter_project_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, null=True)),
                ('country', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='landscape.country')),
            ],
        ),
    ]
