# Generated by Django 5.1.4 on 2025-07-15 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landscape', '0008_abstract'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='abstract',
            options={'verbose_name': 'Abstract', 'verbose_name_plural': 'Abstracts'},
        ),
        migrations.AlterModelOptions(
            name='country',
            options={'verbose_name': 'Country', 'verbose_name_plural': 'Countries'},
        ),
        migrations.AlterModelOptions(
            name='equipement',
            options={'verbose_name': 'Equipement', 'verbose_name_plural': 'Equipement'},
        ),
        migrations.AlterModelOptions(
            name='gedorganism',
            options={'verbose_name': 'GEd Organism', 'verbose_name_plural': 'GEd Organisms'},
        ),
        migrations.AlterModelOptions(
            name='humancapacity',
            options={'verbose_name': 'Human Capacity', 'verbose_name_plural': 'Human Capacities'},
        ),
        migrations.AlterModelOptions(
            name='literature',
            options={'verbose_name': 'Literature', 'verbose_name_plural': 'Literature'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name': 'Organization', 'verbose_name_plural': 'Organizations'},
        ),
        migrations.AlterModelOptions(
            name='regulatoryframework',
            options={'verbose_name': 'Regulatory Framework', 'verbose_name_plural': 'Regulatory Frameworks'},
        ),
        migrations.AlterField(
            model_name='organization',
            name='type',
            field=models.CharField(choices=[('government', 'Government'), ('regulatory', 'Regulatory'), ('university', 'University'), ('research', 'Research'), ('private_sector', 'Private Sector'), ('development_agency', 'Development Agency'), ('igo', 'International Organization'), ('regional_organization', 'Regional Organization'), ('continetal', 'Continental Organization'), ('funding', 'Funding'), ('cso', 'Civil Society Organization')], default='government', max_length=100, verbose_name='Organization Type'),
        ),
        migrations.AlterField(
            model_name='regulatoryframework',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='landscape_regulatory_framework', to='landscape.country'),
        ),
    ]
