# Generated by Django 5.1.4 on 2025-07-15 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('graphs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipmentscore',
            name='equipment',
            field=models.CharField(blank=True, choices=[('sequencer', 'Next-Gen Sequencer'), ('pcr', 'PCR Machine'), ('centrifuge', 'Centrifuge'), ('electrophoresis', 'Electrophoresis'), ('ms', 'Mass Spectrophotometer'), ('laminar_hood', 'Laminar Hood'), ('microscope', 'Fluorescent Microscope'), ('lc', 'Liquid Chromatography'), ('incubator', 'Incubator/Shaker'), ('others', 'Others')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='equipmentscore',
            name='tier',
            field=models.CharField(blank=True, choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='fundedproject',
            name='category',
            field=models.CharField(choices=[('crops', 'Crops'), ('livestock', 'Livestock'), ('microbes', 'Microbes/Soil'), ('marine', 'Marine'), ('fisheries', 'Fisheries'), ('agroforestry', 'Agroforestry')], max_length=20),
        ),
        migrations.AlterField(
            model_name='gedresearchscore',
            name='tier',
            field=models.CharField(blank=True, choices=[('Tier 1', 'Tier 1'), ('Tier 2', 'Tier 2'), ('Tier 3', 'Tier 3')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='staffexpertise',
            name='expertise',
            field=models.CharField(choices=[('abiotic', 'Abiotic Stress'), ('biotic', 'Biotic Stress'), ('animal', 'Animal Science'), ('plant', 'Plant Science'), ('entomology', 'Entomology'), ('ged_technology_efficiency', 'GEd Technology Efficiency'), ('microbiology', 'Microbiology'), ('nutritional', 'Quality Nutritional Traits'), ('yield', 'Yield Productivity Traits'), ('other', 'Other')], max_length=30),
        ),
        migrations.AlterField(
            model_name='staffqualification',
            name='qualification',
            field=models.CharField(choices=[('bsc', 'Bachelor'), ('msc', 'Masters'), ('phd', 'Doctorate'), ('postdoc', 'Postdoc')], max_length=20),
        ),
    ]
